
CREATE TABLE SUBJECT(
    S_Id CHAR(3) PRIMARY KEY,
    Credits INT
);

CREATE TABLE COURSE_SUBJECT(
    S_Id CHAR(3),
    Course_Code CHAR(7),
    FOREIGN KEY(S_Id) REFERENCES SUBJECT(S_Id),
    FOREIGN KEY(Course_Code) REFERENCES COURSE(Course_Code)
);
