CREATE TABLE ATTENDANCE(
	Reg_No CHAR(6),
	TID CHAR(3),
	Count INT,
    FOREIGN KEY (Reg_No) REFERENCES STUDENT(Reg_No),
    FOREIGN KEY (TID) REFERENCES technical_officer(TID)
);

CREATE TABLE MEDICAL(
	Medical_ID CHAR(5) PRIMARY KEY,
	department_id CHAR(5),
	reg_no CHAR(5)
);

CREATE TABLE DEPARTMENT_ADMIN(	
	admin_id CHAR(5),
	department_id CHAR(5)
);

CREATE TABLE STUDENT_EXAM(
	exam_id CHAR(5),
	reg_no CHAR(5)
);