CREATE TABLE ATTENDANCE(
	Reg_No CHAR(6),
	TID CHAR(3),
	Count INT,
    FOREIGN KEY (Reg_No) REFERENCES STUDENT(Reg_No),
    FOREIGN KEY (TID) REFERENCES TECHINICAL_OFFICER(TID)
);

CREATE TABLE MEDICAL(
	Medical_Id CHAR(3) PRIMARY KEY,
	Department_Id CHAR(3),
	Reg_No CHAR(6),
    FOREIGN KEY (Reg_No) REFERENCES STUDENT(Reg_No),
    FOREIGN KEY (Department_Id) REFERENCES DEPARTMENT(Department_Id)
);

CREATE TABLE DEPARTMENT_ADMIN(	
	admin_id CHAR(5),
	department_id CHAR(5)
);

CREATE TABLE STUDENT_EXAM(
	exam_id CHAR(5),
	reg_no CHAR(5)
);