CREATE TABLE ATTENDANCE(
	Reg_No CHAR(6),
	TID CHAR(3),
	Count INT,
    FOREIGN KEY (Reg_No) REFERENCES STUDENT(Reg_No),
    FOREIGN KEY (TID) REFERENCES TECHINICAL_OFFICER(TID)
);

CREATE TABLE MEDICAL(
	Medical_Id CHAR(3) PRIMARY KEY,
	Department_Id CHAR(3),
	Reg_No CHAR(6),
    FOREIGN KEY (Reg_No) REFERENCES STUDENT(Reg_No),
    FOREIGN KEY (Department_Id) REFERENCES DEPARTMENT(Department_Id)
);


CREATE TABLE DEPARTMENT_ADMIN(	
	Admin_Id CHAR(3),
	Department_Id CHAR(3),
    FOREIGN KEY (Admin_Id) REFERENCES ADMIN(Admin_Id),
    FOREIGN KEY (Department_Id) REFERENCES DEPARTMENT(Department_Id)
);

CREATE TABLE STUDENT_EXAM(
	Exam_Id CHAR(3),
	Reg_No CHAR(3),
    FOREIGN KEY (Exam_Id) REFERENCES EXAM(Exam_Id),
    FOREIGN KEY (Reg_No) REFERENCES STUDENT(Reg_No)
);