CREATE TABLE STUDENT(
    Reg_No CHAR(6) NOT NULL,
    State VARCHAR(20),
    User_ID VARCHAR(6),
    PRIMARY KEY(Reg_No),
    FOREIGN KEY (User_ID) REFERENCES user(User_ID)
);

CREATE TABLE LECTURER(
    LID CHAR(3) PRIMARY KEY,
    User_ID VARCHAR(6),
    FOREIGN KEY (User_ID) REFERENCES user(User_ID)
);

CREATE TABLE LECTURER_CONTACT(
    LID CHAR(3),
    Phone_No VARCHAR(11),
    FOREIGN KEY (LID) REFERENCES LECTURER(LID)
);


